Discord Text MMORPG: lua.api.Communication Class Reference
lua.api.Communication Class Reference
Public Member Functions
boolean whisper (String id, String message)
void say (Room location, String message)
void shout (Room location, String message)
String stripID (String str)
Detailed Description
Definition at line 13 of file Communication.java.
Member Function Documentation
say()
void lua.api.Communication.say (Room location, String message)
DMs all Players in a Room.
Parameters
location The Room to propagate the message through.
message The message to send.
See also
world.room.Room
entity.Player
Todo:
Implement this
Definition at line 50 of file Communication.java.
     {
         //channel.sendMessage(message).queue();
         return;
     }
shout()
void lua.api.Communication.shout (Room location, String message)
Sends a message to every Player in a Room via the last channel they were active in. This allows others also in the channel to see the message.
Parameters
location The Room to source the Players from.
message The message to send to the Players.
See also
entity.Player
world.room.Room
Todo:
Implement this
Definition at line 69 of file Communication.java.
     {
         return;
     }
stripID()
String lua.api.Communication.stripID (String str)
A wrapper function for tools.Username.stripID().
Parameters
str The string to parse.
Returns
The ID contained in the string, if any.
See also
tools.Username.stripID()
Definition at line 82 of file Communication.java.
References tools.Username.stripID().
     {
         return Username.stripID(str);
     }
whisper()
boolean lua.api.Communication.whisper (String id, String message)
Sends a message as a DM to the specified player.
Parameters
id The ID of the player to DM.
message The message to send.
Returns
True if the ID is found in the world, false otherwise.
See also
entity.Player
world.World
Definition at line 25 of file Communication.java.
References world.World.getJDA(), and world.World.registered().
Referenced by main.Commands.CommunicationCommands.whisper().
     {
         boolean success = false;
         if (World.registered(id))
         {
             World.getJDA().getUserById(id).openPrivateChannel().queue(
                     (channel) -> channel.sendMessage(message).queue());
             success = true;
         }
         return success;
     }
The documentation for this class was generated from the following file:
Communication.java