Discord Text MMORPG: world.World Class Reference
world.World Class Reference
Static Public Member Functions
static void init (JDA jda_)
static boolean addPlayer (Player p)
static Player findPlayerByID (String id)
static Player findPlayerByName (String username)
static void addRoom (Room r)
static boolean registered (String id)
static ArrayList< Player > getPlayers ()
static JDA getJDA ()
Static Private Attributes
static JDA jda
static ArrayList< Player > players
static ArrayList< Room > rooms
Detailed Description
The World is the universe, as far as the game is concerned. All that exists in the game is kept track of here.
See also
entity.Entity
world.Room
Definition at line 17 of file World.java.
Member Function Documentation
addPlayer()
static boolean world.World.addPlayer (Player p) static
Adds a new Player to the world.
Parameters
p The Player to add.
channel The channel he joined from.
See also
entity.Player
Definition at line 47 of file World.java.
References entity.Player.getID(), entity.Entity.getName(), world.World.registered(), and entity.Entity.setLocation().
Referenced by main.Commands.AdministrativeCommands.register().
     {
         if (registered(p.getID()))
         {
             System.out.println("Warning: Preregistered user tried registering");
             return false;
         }
         players.add(p);
         p.setLocation(rooms.get(0));
         rooms.get(0).addEntity(p);
         System.out.println("Added player " + p.getName() + " with id " + p.getID());
         return true;
     }
addRoom()
static void world.World.addRoom (Room r) static
Definition at line 91 of file World.java.
Referenced by world.Initializer.init().
     {
         rooms.add(r);
         return;
     }
findPlayerByID()
static Player world.World.findPlayerByID (String id) static
Scans the Players currently in the game by their id in order to return a specific one.
Parameters
id The ID to search for.
Returns
The found Player, if any.
See also
entity.Player
Definition at line 73 of file World.java.
Referenced by main.Commands.InteractionCommands.go(), main.Commands.InteractionCommands.look(), main.Commands.InteractionCommands.pickup(), main.Commands.AdministrativeCommands.register(), and main.Commands.CommunicationCommands.whisper().
     {
         for (Player p : players)
             if (p.getID().equals(id))
                 return p;
         return null;
     }
findPlayerByName()
static Player world.World.findPlayerByName (String username) static
Definition at line 82 of file World.java.
Referenced by main.Commands.CommunicationCommands.whisper().
     {
         for (Player p : players)
             if (p.getName().equals(username))
                 return p;
         return null;
     }
getJDA()
static JDA world.World.getJDA () static
Definition at line 111 of file World.java.
References world.World.jda.
Referenced by lua.api.CommunicationDeprecated.Whisper.call(), and lua.api.Communication.whisper().
     {
         return jda;
     }
getPlayers()
static ArrayList<Player> world.World.getPlayers () static
Definition at line 106 of file World.java.
References world.World.players.
     {
         return players;
     }
init()
static void world.World.init (JDA jda_) static
Sets up the world for play.
Parameters
jda_ The Discord connection to keep track of.
Definition at line 28 of file World.java.
References world.Initializer.init().
Referenced by main.Main.main().
     {
         jda = jda_;
         players = new ArrayList<Player>();
         rooms = new ArrayList<Room>();
         Initializer.init();
         return;
     }
registered()
static boolean world.World.registered (String id) static
Definition at line 97 of file World.java.
Referenced by world.World.addPlayer(), lua.api.CommunicationDeprecated.Whisper.call(), main.MainListener.parseMessage(), and lua.api.Communication.whisper().
     {
         for (Player p : players)
             if (p.getID().equals(id))
                 return true;
         return false;
     }
Member Data Documentation
jda
JDA world.World.jda static private
Definition at line 19 of file World.java.
Referenced by world.World.getJDA().
players
ArrayList<Player> world.World.players static private
Definition at line 21 of file World.java.
Referenced by world.World.getPlayers().
rooms
ArrayList<Room> world.World.rooms static private
Definition at line 22 of file World.java.
The documentation for this class was generated from the following file:
World.java