Discord Text MMORPG: world.Initializer Class Reference
world.Initializer Class Reference
Static Public Member Functions
static void init ()
Detailed Description
Definition at line 11 of file Initializer.java.
Member Function Documentation
init()
static void world.Initializer.init () static
Creates a clean world.
See also
world.World
Definition at line 18 of file Initializer.java.
References world.Room.addEntity(), world.Room.addExit(), world.Room.addItem(), world.World.addRoom(), world.RoomType.BUILDING, world.RoomType.ROOM, world.Dir.YN, and world.Dir.YS.
Referenced by world.World.init().
     {
         Room townCenter = new Room("The Town Center", RoomType.ROOM)
                             .addEntity(new Entity("Dummy"))
                             .addItem(new Item("Thing", 0, 1));
         Room aHouse = new Room("A House", RoomType.BUILDING)
                         .addExit(new Door(Dir.YS, "a door", townCenter));
         townCenter.addExit(new Door(Dir.YN, "a house", aHouse));
         World.addRoom(townCenter);
         return;
     }
The documentation for this class was generated from the following file:
Initializer.java