Discord Text MMORPG: world.room.Room Class Reference
world.room.Room Class Reference
Public Member Functions
Room (String name, RoomType type)
String toString ()
Room addExit (Door d)
Room addItem (Item i)
Room addEntity (Entity e)
Room removeEntity (Entity e)
String getName ()
Room setName (String name)
RoomType getType ()
Room setType (RoomType type)
ArrayList< Door > getExits ()
Room setExits (ArrayList< Door > exits)
ArrayList< Item > getItems ()
Room setItems (ArrayList< Item > items)
ArrayList< Entity > getEntities ()
Room setEntities (ArrayList< Entity > entities)
Item searchItem (ArrayList< Item > items, String name)
Private Attributes
String name
RoomType type
ArrayList< Door > exits
ArrayList< Item > items
ArrayList< Entity > entities
Detailed Description
A Room is a space in which Entitys can exist in. They have exits which take the form of Doors and lead to more Rooms.
See also
entity.Entity
world.room.Door
Definition at line 15 of file Room.java.
Constructor & Destructor Documentation
Room()
world.room.Room.Room (String name, RoomType type)
Definition at line 23 of file Room.java.
References world.room.Room.name, and world.room.Room.type.
     {
         this.name = name;
         this.type = type;
         this.exits = new ArrayList();
         this.items = new ArrayList();
         this.entities = new ArrayList();
     }
Member Function Documentation
addEntity()
Room world.room.Room.addEntity (Entity e)
Definition at line 130 of file Room.java.
Referenced by world.Initializer.init(), and entity.Player.move().
     {
         entities.add(e);
         return this;
     }
addExit()
Room world.room.Room.addExit (Door d)
Definition at line 118 of file Room.java.
Referenced by world.Initializer.init().
     {
         exits.add(d);
         return this;
     }
addItem()
Room world.room.Room.addItem (Item i)
Definition at line 124 of file Room.java.
Referenced by world.Initializer.init().
     {
         items.add(i);
         return this;
     }
getEntities()
ArrayList<Entity> world.room.Room.getEntities ()
Definition at line 186 of file Room.java.
References world.room.Room.entities.
     {
         return entities;
     }
getExits()
ArrayList<Door> world.room.Room.getExits ()
Definition at line 164 of file Room.java.
References world.room.Room.exits.
Referenced by entity.Player.move().
     {
         return exits;
     }
getItems()
ArrayList<Item> world.room.Room.getItems ()
Definition at line 175 of file Room.java.
References world.room.Room.items.
Referenced by main.Commands.InteractionCommands.pickup().
     {
         return items;
     }
getName()
String world.room.Room.getName ()
Definition at line 142 of file Room.java.
References world.room.Room.name.
     {
         return name;
     }
getType()
RoomType world.room.Room.getType ()
Definition at line 153 of file Room.java.
References world.room.Room.type.
     {
         return type;
     }
removeEntity()
Room world.room.Room.removeEntity (Entity e)
Definition at line 136 of file Room.java.
Referenced by entity.Player.move().
     {
         entities.remove(e);
         return this;
     }
searchItem()
Item world.room.Room.searchItem (ArrayList< Item > items, String name)
Definition at line 197 of file Room.java.
Referenced by main.Commands.InteractionCommands.pickup().
     {
         for (Item i : items)
             if (i.getName().equals(name))
                 return i;
         return null;
     }
setEntities()
Room world.room.Room.setEntities (ArrayList< Entity > entities)
Definition at line 191 of file Room.java.
References world.room.Room.entities.
     {
         this.entities = entities;
         return this;
     }
setExits()
Room world.room.Room.setExits (ArrayList< Door > exits)
Definition at line 169 of file Room.java.
References world.room.Room.exits.
     {
         this.exits = exits;
         return this;
     }
setItems()
Room world.room.Room.setItems (ArrayList< Item > items)
Definition at line 180 of file Room.java.
References world.room.Room.items.
     {
         this.items = items;
         return this;
     }
setName()
Room world.room.Room.setName (String name)
Definition at line 147 of file Room.java.
References world.room.Room.name.
     {
         this.name = name;
         return this;
     }
setType()
Room world.room.Room.setType (RoomType type)
Definition at line 158 of file Room.java.
References world.room.Room.type.
     {
         this.type = type;
         return this;
     }
toString()
String world.room.Room.toString ()
Gives a view of the Room, listing all Doors, Entitys, and Items.
Returns
A string containing the view from inside the room.
Todo:
Add more grammar support, such as an egg vs a toaster.
Definition at line 41 of file Room.java.
References world.room.RoomType.BUILDING, and world.room.RoomType.ROOM.
Referenced by entity.Player.look().
     {
         StringBuilder sb = new StringBuilder();
         sb.append("You are in " + this.name + ".\n\n");
         if (items.size() > 0)
         {
             sb.append("You can see");
             char header = 'a';
             if (items.size() > 1)
             {
                 sb.append(":\n");
                 header = 'A';
             }
             else
                 sb.append(" ");
             for (Item i : items)
             {
                 sb.append(header);
                 if ("aeiou".contains(i.getName().toLowerCase().subSequence(0, 1)))
                     sb.append("n");
                 sb.append(" " + i.getName() + "\n");
             }
             sb.append("\n");
         }
         if (entities.size() > 0)
         {
             sb.append("There is");
             char header = 'a';
             if (entities.size() > 1)
             {
                 sb.append(":\n");
                 header = 'A';
             }
             else
                 sb.append(" ");
             for (Entity e : entities)
             {
                 sb.append(header);
                 if ("aeiou".contains(e.getName().toLowerCase().subSequence(0, 1)))
                     sb.append("n");
                 sb.append(" " + e.getName() + "\n");
             }
             sb.append(" ");
         }
         sb.append("\n");
         for (Door d : exits)
         {
             if (d.getDestination().getType() == RoomType.ROOM)
             {
                 //if ("aeiou".contains(d.getDescription()))
                 sb.append("To " + d.getDirection() + " lies " + d.getDescription() + "\n");
             }
             else if (d.getDestination().getType() == RoomType.BUILDING)
                 sb.append("There is " + d.getDestination().getName() + "\n");
             else
             {
                 System.out.println("Critical Error: Unknown room type: " + d.getDestination().getType());
                 return "";
             }
         }
         return sb.toString();
     }
Member Data Documentation
entities
ArrayList<Entity> world.room.Room.entities private
Definition at line 21 of file Room.java.
Referenced by world.room.Room.getEntities(), and world.room.Room.setEntities().
exits
ArrayList<Door> world.room.Room.exits private
Definition at line 19 of file Room.java.
Referenced by world.room.Room.getExits(), and world.room.Room.setExits().
items
ArrayList<Item> world.room.Room.items private
Definition at line 20 of file Room.java.
Referenced by world.room.Room.getItems(), and world.room.Room.setItems().
name
String world.room.Room.name private
Definition at line 17 of file Room.java.
Referenced by world.room.Room.getName(), world.room.Room.Room(), and world.room.Room.setName().
type
RoomType world.room.Room.type private
Definition at line 18 of file Room.java.
Referenced by world.room.Room.getType(), world.room.Room.Room(), and world.room.Room.setType().
The documentation for this class was generated from the following file:
Room.java