Discord Text MMORPG: main.Commands.CommunicationCommands Class Reference
main.Commands.CommunicationCommands Class Reference
Static Public Member Functions
static void whisper (String id, String[] words, MessageChannel channel)
Detailed Description
Definition at line 8 of file CommunicationCommands.java.
Member Function Documentation
whisper()
static void main.Commands.CommunicationCommands.whisper (String id, String [] words, MessageChannel channel) static
Definition at line 10 of file CommunicationCommands.java.
References world.World.findPlayerByID(), world.World.findPlayerByName(), entity.Player.getID(), entity.Entity.getName(), and lua.api.Communication.whisper().
Referenced by main.MainListener.registeredCommand().
     {
         if (words.length < 3)
         {
             channel.sendMessage("Correct usage: `>whisper <username> <message>`").queue();
             return;
         }
         String sendee = words[1];
         String msg = words[2];
         for (int i = 3; i < words.length; i++)
             msg += " " + words[i];
         Player recipient = World.findPlayerByName(sendee);
         if (recipient == null)
         {
             channel.sendMessage("Player " + sendee + " not found.").queue();
             return;
         }
         String sender = World.findPlayerByID(id).getName();
         new Communication().whisper(recipient.getID(), sender + ": " + msg);
         return;
     }
The documentation for this class was generated from the following file:
CommunicationCommands.java