Discord Text MMORPG: main.Commands.AdministrativeCommands Class Reference
main.Commands.AdministrativeCommands Class Reference
Static Public Member Functions
static void register (String id, String[] words, MessageChannel channel)
Detailed Description
Definition at line 7 of file AdministrativeCommands.java.
Member Function Documentation
register()
static void main.Commands.AdministrativeCommands.register (String id, String [] words, MessageChannel channel) static
Definition at line 9 of file AdministrativeCommands.java.
References world.World.addPlayer(), world.World.findPlayerByID(), and entity.Entity.getName().
Referenced by main.MainListener.unregisteredCommand().
     {
         if (words.length < 2)
         {
             channel.sendMessage("Correct usage: `> register myUsername`").queue();
             return;
         }
         else if (words.length > 2)
         {
             channel.sendMessage("Usernames must not contain spaces").queue();
             return;
         }
         Player p = World.findPlayerByID(id);
         if (p == null)
         {
             p = new Player(words[1], id);
             if (World.addPlayer(p))
                 channel.sendMessage("Welcome to the world, " + p.getName() +
                         "!\nTry looking around with `> look`").queue();
             else
                 channel.sendMessage("You're already registered!").queue();
         }
         else
             channel.sendMessage("You're already registered as " + p.getName()).queue();
         return;
     }
The documentation for this class was generated from the following file:
AdministrativeCommands.java