Discord Text MMORPG: main.Main Class Reference
main.Main Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static String getKey ()
Detailed Description
Definition at line 24 of file Main.java.
Member Function Documentation
getKey()
static String main.Main.getKey () static private
Loads in the bot token from the key file. Prevents the token from being anywhere in the code.
Returns
The token, if found. Otherwise, an empty string.
Definition at line 32 of file Main.java.
Referenced by main.Main.main().
     {
         String key  = "";
         try
         {
             key = Files.readAllLines(Paths.get("key")).get(0);
         }
         catch (IOException e) {}
         return key;
     }
main()
static void main.Main.main (String [] args) static
Connects the bot to the Discord servers and then initializes the world.
Parameters
args Unusued launch arguments
See also
world.World
world.Initializer
Definition at line 52 of file Main.java.
References main.Main.getKey(), and world.World.init().
     {
         JDA api = null;
         String key = getKey();
         if (key.isEmpty())
         {
             System.out.println("Keyfile not found!");
             return;
         }
         try
         {
             api = new JDABuilder(key)
                     .addEventListener(new MainListener())
                     .build();
         }
         catch (LoginException e)
         {
             e.printStackTrace();
         }
         World.init(api);
         //Parser.run("");
         System.out.println("Classpaths: ");
         ClassLoader cl = ClassLoader.getSystemClassLoader();
         URL[] urls = ((URLClassLoader)cl).getURLs();
         for(URL url: urls){
             System.out.println(url.getFile());
         }
     }
The documentation for this class was generated from the following file:
Main.java