Discord Text MMORPG: main.MainListener Class Reference
main.MainListener Class Reference
Public Member Functions
void onMessageReceived (MessageReceivedEvent event)
Private Member Functions
void parseMessage (MessageReceivedEvent event, MessageChannel channel, Message message, String content)
Static Private Member Functions
static boolean unregisteredCommand (MessageReceivedEvent event, MessageChannel channel, String[] words)
static boolean registeredCommand (MessageReceivedEvent event, MessageChannel channel, String[] words)
Detailed Description
Definition at line 19 of file MainListener.java.
Member Function Documentation
onMessageReceived()
void main.MainListener.onMessageReceived (MessageReceivedEvent event)
Preliminary filtering of messages. Discards messages from bots, and messages which don't start with a >.
Definition at line 26 of file MainListener.java.
References main.MainListener.parseMessage().
     {
         if (event.getAuthor().isBot())
         {
             // System.out.println("Blocked a message from a bot");
             return;
         }
         Message message = event.getMessage();
         MessageChannel channel = event.getChannel();
         String content = message.getContentRaw();
         if (content.length() > 0 && content.charAt(0) == '>')
         {
             System.out.println("Received a command: " + content);
             parseMessage(event, channel, message, content);
         }
         else if (event.getChannel().getType() == ChannelType.PRIVATE)
         {
             System.out.println("Received DM from " +
                     event.getAuthor().getName() + ":\n\t" +
                     event.getMessage().getContentRaw());
         }
         return;
     }
parseMessage()
void main.MainListener.parseMessage (MessageReceivedEvent event, MessageChannel channel, Message message, String content) private
Given a message which we know for sure is directed at the bot, try and figure out which command the user was trying to run.
Parameters
event The main message event.
channel The channel the message came from.
message The message object itself.
content The message body.
Definition at line 63 of file MainListener.java.
References world.World.registered(), main.MainListener.registeredCommand(), and main.MainListener.unregisteredCommand().
Referenced by main.MainListener.onMessageReceived().
     {
         while (content.length() > 0 &&
                 (content.charAt(0) == '>' || content.charAt(0) == ' '))
         {
             content = content.substring(1);
         }
         String[] words = content.split(" ");
         if (words.length == 0)
         {
             System.out.println("Warning: Empty command");
             return;
         }
         if (!unregisteredCommand(event, channel, words))
         {
             if (!World.registered(event.getAuthor().getId()))
             {
                 channel.sendMessage("Please register first with `> register`!").queue();
                 return;
             }
             else
             {
                 if (!registeredCommand(event, channel, words))
                     channel.sendMessage("You don't know what that means").queue();
             }
         }
         return;
     }
registeredCommand()
static boolean main.MainListener.registeredCommand (MessageReceivedEvent event, MessageChannel channel, String [] words) static private
Tries to see if the user ran a command which requires registration.
Parameters
event The message event.
channel The channel the message was sent in.
message The message event.
words The preparsed word list.
Returns
True if a command was run, false otherwise.
Definition at line 136 of file MainListener.java.
References lua.Parser.extractCode(), main.Commands.InteractionCommands.go(), main.Commands.InteractionCommands.look(), main.Commands.InteractionCommands.pickup(), lua.Parser.run(), and main.Commands.CommunicationCommands.whisper().
Referenced by main.MainListener.parseMessage().
     {
         String id = event.getAuthor().getId();
         switch(words[0])
         {
             case "look":
                 InteractionCommands.look(id, channel);
                 return true;
             case "whisper":
                 CommunicationCommands.whisper(id, words, channel);
                 return true;
             case "pickup":
                 InteractionCommands.pickup(id, words, channel);
                 return true;
             case "go":
             case "goto":
                 InteractionCommands.go(id, words[1], channel);
                 return true;
             case "cast":
                 Parser.run(Parser.extractCode(event.getMessage().getContentRaw()));
                 return true;
             default:
                 System.out.println("Warning: Unknown comand header " + words[0]);
                 return false;
         }
     }
unregisteredCommand()
static boolean main.MainListener.unregisteredCommand (MessageReceivedEvent event, MessageChannel channel, String [] words) static private
Tries to see if the user ran a command which does not require registration.
Parameters
event The message event.
channel The channel the message was sent in.
message The message event.
words The preparsed word list.
Returns
True if a command was run, false otherwise.
Definition at line 106 of file MainListener.java.
References main.Commands.AdministrativeCommands.register().
Referenced by main.MainListener.parseMessage().
     {
         String id = event.getAuthor().getId();
         switch(words[0])
         {
             case "ping":
                 channel.sendMessage("pong!").queue();
                 return true;
             case "register":
                 AdministrativeCommands.register(id, words, channel);
                 return true;
             default:
                 return false;
         }
     }
The documentation for this class was generated from the following file:
MainListener.java