Discord Text MMORPG: entity.Player Class Reference
entity.Player Class Reference
Public Member Functions
Player (String name, String id)
String look ()
boolean move (String goal)
void addItem (Item item)
String getID ()
Public Member Functions inherited from entity.Entity
Entity (String name)
Entity (String name, Room Location)
Room getLocation ()
Entity setLocation (Room location)
String getName ()
Entity setName (String name)
Private Attributes
String id
The unique Discord ID associated with every account.
long xp
The experience points the player has.
int level
The current level of the player.
ArrayList< Item > inventory
Additional Inherited Members
Protected Attributes inherited from entity.Entity
Room location
The Room this Entity resides in.
String name
The name of this Entity.
Detailed Description
Definition at line 14 of file Player.java.
Constructor & Destructor Documentation
Player()
entity.Player.Player (String name, String id)
Definition at line 29 of file Player.java.
References entity.Player.id.
     {
         super(name);
         this.id = id;
         this.inventory = new ArrayList<>();
         this.xp = 0;
     }
Member Function Documentation
addItem()
void entity.Player.addItem (Item item)
Definition at line 79 of file Player.java.
Referenced by main.Commands.InteractionCommands.pickup().
     {
         inventory.add(item);
         return;
     }
getID()
String entity.Player.getID ()
Definition at line 85 of file Player.java.
References entity.Player.id.
Referenced by world.World.addPlayer(), and main.Commands.CommunicationCommands.whisper().
     {
         return id;
     }
look()
String entity.Player.look ()
Returns a textual picture of everything going on in the current Room, given by the player's location.
Returns
The string containing the textual description of the location.
See also
entity.Player.location
Definition at line 46 of file Player.java.
References entity.Entity.location, and world.room.Room.toString().
Referenced by main.Commands.InteractionCommands.look().
     {
         return location.toString();
     }
move()
boolean entity.Player.move (String goal)
Tries to move from the current location to a new one. The destination is given by the goal parameter. A match is performed by searching if the goal is anywhere in the potential exits from the player's current location.
Parameters
goal A string containing a search sequence to search the exits for.
Returns
True if the move was successful, false otherwise.
Definition at line 61 of file Player.java.
References world.room.Room.addEntity(), world.room.Room.getExits(), entity.Entity.location, and world.room.Room.removeEntity().
Referenced by main.Commands.InteractionCommands.go().
     {
         for (Door d : location.getExits())
         {
             if (d.getDirection().toLowerCase().contains(goal.toLowerCase()) ||
                     d.getDestination().getName().toLowerCase().contains(goal.toLowerCase()) ||
                     d.getDescription().toLowerCase().contains(goal.toLowerCase()))
             {
                 this.location.removeEntity(this);
                 this.location = d.getDestination();
                 this.location.addEntity(this);
                 return true;
             }
         }
         return false;
     }
Member Data Documentation
id
String entity.Player.id private
The unique Discord ID associated with every account.
Definition at line 17 of file Player.java.
Referenced by entity.Player.getID(), and entity.Player.Player().
inventory
ArrayList<Item> entity.Player.inventory private
The list of Items owned by the player.
See also
item.Item
Definition at line 27 of file Player.java.
level
int entity.Player.level private
The current level of the player.
Definition at line 23 of file Player.java.
xp
long entity.Player.xp private
The experience points the player has.
Definition at line 20 of file Player.java.
The documentation for this class was generated from the following file:
Player.java