Discord Text MMORPG: main.Commands.InteractionCommands Class Reference
main.Commands.InteractionCommands Class Reference
Static Public Member Functions
static void go (String id, String destination, MessageChannel channel)
static void pickup (String id, String[] words, MessageChannel channel)
static void look (String id, MessageChannel channel)
Detailed Description
Definition at line 9 of file InteractionCommands.java.
Member Function Documentation
go()
static void main.Commands.InteractionCommands.go (String id, String destination, MessageChannel channel) static
Definition at line 11 of file InteractionCommands.java.
References world.World.findPlayerByID(), and entity.Player.move().
Referenced by main.MainListener.registeredCommand().
     {
         if (!World.findPlayerByID(id).move(destination))
             channel.sendMessage("You aren't sure where that is.").queue();
         return;
     }
look()
static void main.Commands.InteractionCommands.look (String id, MessageChannel channel) static
Definition at line 52 of file InteractionCommands.java.
References world.World.findPlayerByID(), and entity.Player.look().
Referenced by main.MainListener.registeredCommand().
     {
         channel.sendMessage(World.findPlayerByID(id).look()).queue();
         return;
     }
pickup()
static void main.Commands.InteractionCommands.pickup (String id, String [] words, MessageChannel channel) static
Definition at line 19 of file InteractionCommands.java.
References entity.Player.addItem(), world.World.findPlayerByID(), world.room.Room.getItems(), entity.Entity.getLocation(), and world.room.Room.searchItem().
Referenced by main.MainListener.registeredCommand().
     {
         ArrayList<Item> lst = World.findPlayerByID(id).getLocation().getItems();
         if (words.length <= 1)
         {
             channel.sendMessage("Warning: Not enough information!").queue();
             return;
         }
         String itemName = "";
         for (int i = 1; i < words.length; i++)
         {
             itemName += words[i];
             if (i == words.length - 1)
                 break;
             itemName += " ";
         }
         Item item = World.findPlayerByID(id).getLocation().searchItem(lst, itemName);
         if (item!= null)
         {
             World.findPlayerByID(id).addItem(item);
             channel.sendMessage("You have picked up the " + itemName + "!").queue();
             lst.remove(item);
             return;
         }
         else
         {
             channel.sendMessage(itemName + " not found!").queue();
             return;
         }
     }
The documentation for this class was generated from the following file:
InteractionCommands.java